### ISSUE TITLE
allow specifying image DPI

### ISSUE THREAD

**Issue by wydengyre** [robertknight/tesseract-wasm#45]
It should be possible to specify image DPI rather than relying on resolution estimation.

**Comment by robertknight** [comment]
I think this should be easy enough to add. Do you have examples of images where the estimation is significantly incorrect?

**Comment by wydengyre** [comment]
> I think this should be easy enough to add. Do you have examples of images where the estimation is significantly incorrect?

I do have such examples, working with Japanese film subtitles. The estimation varies wildly from one set of subtitles to the next. I'll upload some concrete examples when I have a moment, soon.

It's also a bit annoying that the estimation polutes the console with logging, though perhaps that ought to be addressed separately.

I'd like to make a PR that addresses this, and other such potential issues, by exposing the `SetVariable` API through `OCREngine`. What do you think?

**Comment by robertknight** [comment]
For DPI specifically there is a `SetSourceResolution` API, which could be exposed as an optional parameter to `loadImage` (eg. `engine.loadImage(image, { dpi: resolution })`).

I'd be OK with exposing `SetVariable` as a power-user API, although I suspect there are options which won't work properly in the constrained browser environment (eg. no filesystem), so this configuration would be exposed on a "buyer beware" basis.

**Comment by wydengyre** [comment]
> For DPI specifically there is a `SetSourceResolution` API, which could be exposed as an optional parameter to `loadImage` (eg. `engine.loadImage(image, { dpi: resolution })`).

I think this makes sense, though it gives me pause from an API design standpoint... Particularly, it's hard for me to judge which aspects of the tesseract API deserve to be promoted to (optional) parameters of `loadImage`. It makes me a bit reluctant to make such a PR myself. My instinct would be to follow the API of tesseract itself as closely as possible.

For my purposes, an all-around power-user `SetVariable` API would more than do the trick, in any case.
