### ISSUE TITLE
peg emsdk version

### ISSUE THREAD

**Issue by wydengyre** [robertknight/tesseract-wasm#53]
It seems that the following line will always install the latest tagged emsdk release: https://github.com/robertknight/tesseract-wasm/blob/534e5f7df602a432e5e61ee1dcc832c72a80fe4c/Makefile#L67

It looks like this might make builds non-deterministic. Should it be changed to a specific version?

**Comment by wydengyre** [comment]
I'm also wondering, now, if it's even necessary to install/activate emsdk this way, or if it can be run right out of the `third_party/emsdk` directory.

**Comment by robertknight** [comment]
> It looks like this might make builds non-deterministic. Should it be changed to a specific version?
> I'm also wondering, now, if it's even necessary to install/activate emsdk this way, or if it can be run right out of the third_party/emsdk directory.

I don't know the answers to these two questions. If the build i not deterministic, it would be good to make them so. If it is possible to avoid the install/activate steps, without complicating the rest of the build, that would also be good.

**Comment by robertknight** [comment]
> It looks like this might make builds non-deterministic. Should it be changed to a specific version?

I looked into the way the `latest` version gets resolved. It is specified in a [JSON config file](https://github.com/emscripten-core/emsdk/blob/main/emscripten-releases-tags.json) that is part of the emsdk package, so if you check out the emsdk repo at a specific commit, as we are doing, `latest` will always resolve to the same version - currently "3.1.15". So the build is actually deterministic/repeatable, as long as `latest` is handled in the same way.

**Comment by wydengyre** [comment]
Ah, excellent. Thanks for figuring this out.
