### ISSUE TITLE
[not an actual issue] thank you for this amazing project!!

### ISSUE THREAD

**Issue by gregsadetsky** [robertknight/tesseract-wasm#89]
that's all -- thank you for making it and sharing it!!

I combined it with [pdf.js](https://mozilla.github.io/pdf.js/) to make an in-browser pdf-to-text ocr converter -> [https://pdf.greg.technology/](https://pdf.greg.technology/) it works well & is super fast!! thank you again

**Comment by robertknight** [comment]
Glad you found this useful :)
